### ISSUE TITLE
Meta Refresh Header problem in HtmlUnit 

### ISSUE THREAD

**Issue by asevans48** [HtmlUnit/temp#1]
When running into a meta refresh,HTML Unit is going into an infinite loop. I think it may be reading the location header in the Refresh when tags like <meta name="refresh" content="0;url=...."/> are present or the Refresh header exists. In my case, performing a simple search on https://www.sotar.us/sotar-public/
publicIndexRedirect.do is causing major problems.

**Comment by asashour** [comment]
Thanks for reporting, fixed in SVN.

Please use the [bug tracker](https://sourceforge.net/p/htmlunit/bugs/) for future reports.
